#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2bf23eaf-840c-480e-afea-2c9a4c0a0425 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int vibration_sensor;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

int l = D2;
int vs =D0;

void setup() {
    pinMode(l, OUTPUT);
  pinMode(vs, INPUT); 
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  vibration_sensor = vibration();
    delay(50);
  Serial.println(vibration_sensor);
  if (vibration_sensor > 50){
    digitalWrite(l, HIGH);
  }
  else{
    digitalWrite(l, LOW); 
  }
  
  if(vibration_sensor>5000){
    led = 1;
  }
  else{
    led = 0;
  }
  
}


/*
  Since VibrationSensor is READ_WRITE variable, onVibrationSensorChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVibrationSensorChange()  {
  
    vibration_sensor = vibration();
    delay(50);
    Serial.println(vibration_sensor);
  
  // Add your code here to act upon VibrationSensor change  
  
}


int vibration(){
  int measurement=pulseIn (vs,HIGH);  //wait for the pin to get HIGH and returns measurement
  return measurement;
}

